# Generated by Django 6.0.5 on 2026-06-17 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourseStepProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progresses', to='learning.resourcestep')),
                ('user_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_progresses', to='learning.usercourse')),
            ],
            options={
                'ordering': ['step__order'],
                'unique_together': {('user_course', 'step')},
            },
        ),
    ]
