# Generated by Django 6.0.5 on 2026-05-22 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourse',
            name='progress_percent',
        ),
        migrations.AlterField(
            model_name='resource',
            name='duration_minutes',
            field=models.CharField(blank=True, choices=[('short', 'کوتاه'), ('medium', 'متوسط'), ('long', 'بلند مدت'), ('too long', 'طولانی مدت')], default='short', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('video', 'فیلم'), ('article', 'مقاله'), ('course', 'کورس'), ('podcast', 'صوتی-پادکست')], max_length=20),
        ),
        migrations.CreateModel(
            name='ResourceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='learning.resource')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('resource', 'order')},
            },
        ),
        migrations.AddField(
            model_name='usercourse',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.resourcestep'),
        ),
    ]
