# Generated by Django 6.0.5 on 2026-05-27 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_skill_image_subskill_resource_subskill_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='subskill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='learning.subskill'),
            preserve_default=False,
        ),
    ]
